services:
  wzam_api:
    build:
      context: ./api
    image: wzam_api:latest
    restart: always
    ports:
      - '8080:8080'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}

      KEYCLOAK_ENDPOINT: http://${KEYCLOAK_DOMAIN}:8084/
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_NAME: ${KEYCLOAK_API_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_API_CLIENT_SECRET_KEY}

      LOGGING_LEVEL: ${API_LOGGING_LEVEL}
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  wzam_postgres:
    image: postgis/postgis:15-master
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdb:/var/lib/postgresql/data
      - ./resources/sql_scripts:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: '10m'

  wzam_keycloak:
    image: wzam_keycloak:latest
    build:
      context: ./resources/keycloak
    restart: always
    ports:
      - "8084:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    logging:
      options:
        max-size: "10m"
    volumes:
      - keycloak:/opt/keycloak/data/

volumes:
  pgdb:
    driver: local
  keycloak:
